### PR TITLE
added grunt-exec and use instead of grunt-shell

### PR DESCRIPTION
**Pull request by paulohp**
It should be resolves the #58, #43, and #48

### CODE REVIEW

**Comment by paulohp** [comment]
@zenorocha @eduardolundgren do you guys have any comments here? thanks!

**Comment by msaglietto** [comment]
Hi @paulohp  thanks for the pr but  is not solving #58 for me on El Capitan

**Comment by mingomax** [comment]
Hi! Please we have some news about this problem? Or what alternative we have to solve this?

**Comment by zenorocha** [comment]
Not yet @mingomax. As you noticed we're focused in other projects now. I recommend you checking the [templates](https://github.com/eduardolundgren/dotfiles/tree/master/templates) separately until we find some time to come back and fix these issues.

**Comment by zenorocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
